routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\CourceController;
use App\Http\Controllers\PaymentController;
use Stichoza\GoogleTranslate\GoogleTranslate;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\NursingRecruitmentController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\RazorpayController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     $tr = new GoogleTranslate(); // Translates to 'en' from auto-detected language by default
//     $tr->setSource('fr');
//     return $tr->translate('Hello World!');
//     return view('welcome');
// });

Route::get('/', [TemplateController::class, 'Home'])->name('/');
// Route::get('login', [TemplateController::class, 'login'])->name('login');
Route::get('checkout', [TemplateController::class, 'checkouts'])->name('checkout');
Route::post('checkout', [TemplateController::class, 'addUser'])->name('checkout');
Route::get('resetpassword', [TemplateController::class, 'resetpassword'])->name('resetpassword');
Route::get('take-course', [CourceController::class, 'checkouts'])->name('take-course');
Route::get('contact-us', [TemplateController::class, 'contactUs'])->name('contact-us');
Route::get('privacy-policy', [TemplateController::class, 'privacyPolicy'])->name('privacy-policy');
Route::get('pricing', [TemplateController::class, 'pricing'])->name('pricing');
Route::get('about-us', [TemplateController::class, 'aboutUs'])->name('about-us');
Route::get('terms-condition', [TemplateController::class, 'termsCondition'])->name('terms-condition');
Route::get('psc-coaching', [TemplateController::class, 'pscCoaching'])->name('psc-coaching');
Route::get('ket-coaching', [TemplateController::class, 'ketCoaching'])->name('ket-coaching');

Route::post('payment', [PaymentController::class, 'index'])->name('payment');
Route::post('payment-verify', [PaymentController::class, 'paymentVerify'])->name('payment-verify');
Route::post('payment-response', [PaymentController::class, 'paymentResponse'])->name('payment-response');
Route::get('refund-order', [PaymentController::class, 'refundOrder'])->name('refund-order');

Route::get('lang/{lang}', ['as' => 'lang.switch', 'uses' => 'App\Http\Controllers\LanguageController@switchLang']);

// Route::middleware(['auth:sanctum', 'verified', 'isUser'])->get('/userdashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::middleware(['auth:sanctum', 'verified', 'isUser'])->group(function () {
  Route::get('userdashboard', [CourceController::class, 'index'])->name('dashboard');
  Route::get('docdownload/{filename}', [CourceController::class, 'docdownload'])->name('docdownload'); 
  Route::get('docview/{filename}', [CourceController::class, 'docview'])->name('docview'); 
  // Route::get('documentview', [AdminController::class, 'documentview'])->name('admin.documentview');
});

Route::middleware(['auth', 'isAdmin'])->group(function () {
    Route::get('admin', [AdminController::class, 'index'])->name('admin');
    Route::get('dashboard', [AdminController::class, 'index'])->name('admin.dashboard');
    Route::get('users', [AdminController::class, 'getUsers'])->name('admin.getUsers');
    Route::get('Meeting', [AdminController::class, 'Meeting'])->name('admin.Meeting');
    Route::post('crtMeeting', [AdminController::class, 'crtMeeting'])->name('admin.crtMeeting');
    Route::get('dateRange', [AdminController::class, 'dateRange'])->name('admin.dateRange');
    Route::get('ParticipantsView/{id}', [AdminController::class, 'ParticipantsView'])->name('admin.ParticipantsView');
    Route::get('getMeetings', [AdminController::class, 'getMeetings'])->name('admin.getMeetings');  
    Route::get('viewParticipants/{id}', [AdminController::class, 'viewParticipants'])->name('admin.viewParticipants');
    Route::get('editMeeting/{id}', [AdminController::class, 'editMeeting'])->name('admin.editMeeting');
    Route::post('meetingupdate/{id}', [AdminController::class, 'meetingupdate'])->name('admin.meetingupdate');
    Route::get('getCandidates', [AdminController::class, 'getCandidates'])->name('admin.getCandidates');    
    Route::get('download/{filename}', [AdminController::class, 'download'])->name('admin.download'); 
    Route::get('getHospitals', [AdminController::class, 'getHospitals'])->name('admin.getHospitals');  
    Route::get('getHospitallist', [AdminController::class, 'getHospitallist'])->name('admin.getHospitallist'); 
    Route::get('addHospital', [AdminController::class, 'addHospital'])->name('admin.addHospital'); 
    Route::post('addHos', [AdminController::class, 'addHos'])->name('admin.addHos');   
    Route::get('view/{id}', [AdminController::class, 'view'])->name('admin.view');
    Route::get('edit/{id}', [AdminController::class, 'edit'])->name('admin.edit');
    Route::get('delete/{id}', [AdminController::class, 'delete'])->name('admin.delete');
    Route::post('update/{id}', [AdminController::class, 'update'])->name('admin.update');
    Route::get('getEduloanUsers', [AdminController::class, 'getEduloanUsers'])->name('admin.getEduloanUsers');    
    Route::get('profileView/{id}', [AdminController::class, 'profileView'])->name('admin.profileView');
    Route::post('selectedHospital', [AdminController::class, 'selectedHospital'])->name('admin.selectedHospital');
    Route::get('getApplications', [AdminController::class, 'getApplications'])->name('admin.getApplications');
    Route::post('selectedList', [AdminController::class, 'selectedList'])->name('admin.selectedList');
    Route::get('getShortlistedCandidate', [AdminController::class, 'getShortlistedCandidate'])->name('admin.getShortlistedCandidate');
    Route::post('replyEmail', [AdminController::class, 'replyEmail'])->name('admin.replyEmail');
    Route::post('candidateDocUpload', [AdminController::class, 'candidateDocUpload'])->name('admin.candidateDocUpload');
  });

Route::get('recruitment', [NursingRecruitmentController::class, 'index'])->name('recruitment');
Route::post('recruit', [NursingRecruitmentController::class, 'store'])->name('recruit');

Route::post('razorpaypayment', [RazorpayController::class, 'razorpaypayment'])->name('razorpaypayment');

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <!-- <x-jet-welcome /> -->
                <!-- Styles -->
                <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&display=swap" rel="stylesheet">
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
                <link href="{{ asset('dashboard-theme/assets/plugins/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
                <link href="{{ asset('dashboard-theme/assets/plugins/font-awesome/css/all.min.css') }}" rel="stylesheet"> 

                <!-- Theme Styles -->
                <link href="{{ asset('dashboard-theme/assets/css/lime.min.css') }}" rel="stylesheet">
                <link href="{{ asset('dashboard-theme/assets/css/custom.css') }}" rel="stylesheet">

                <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
                <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
                <!--[if lt IE 9]>
                <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
                <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
                <![endif]-->
                <div class="lime-container">
                    <div class="lime-body">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="card bg-info text-white">
                                        <div class="card-body">
                                            <div class="dashboard-info row">
                                                <div class="info-text col-md-6">
                                                    <h5 class="card-title">Welcome back {{ Auth::user()->firstname}}</h5>
                                                    <p>Get alert for the notification alert for the class.</p>
                                                    <ul>
                                                        <li>We conducting class for the guidence of taking edu-loan.</li>
                                                        <li>Supporting for collecting data</li>
                                                        <li>Supporting for the paper work.</li>
                                                    </ul>
                                                </div>
                                                <div class="info-image col-md-6"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>      
                                <div class="col-md-4">
                                    <div class="card">
                                        <div class="card-body">
                                            <div class="">
                                                <div class="">
                                                    <h5 class="card-title">Daily Visitors</h5>
                                                    <canvas id="visitorsChart"></canvas>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>                      
                            </div>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="card stat-card">
                                        <div class="card-body">
                                            <h5 class="card-title">Class attended</h5>
                                            <h2 class="float-right">0</h2>
                                            <p>From last week</p>
                                            <div class="progress" style="height: 10px;">
                                                <div class="progress-bar bg-warning" role="progressbar" style="width: 45%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="card stat-card">
                                        <div class="card-body">
                                            <h5 class="card-title">Orders</h5>
                                            <h2 class="float-right">14.3K</h2>
                                            <p>Orders in waitlist</p>
                                            <div class="progress" style="height: 10px;">
                                                <div class="progress-bar bg-info" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="card stat-card">
                                        <div class="card-body">
                                            <h5 class="card-title">Monthly Profit</h5>
                                            <h2 class="float-right">45.6$</h2>
                                            <p>For last 30 days</p>
                                            <div class="progress" style="height: 10px;">
                                                <div class="progress-bar bg-success" role="progressbar" style="width: 45%" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @if(Session::get('user_data'))
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="card">
                                        <div class="card-body">
                                            <h5 class="card-title">Offer Letters</h5>
                                            <div class="table-responsive">
                                                <table class="table">
                                                    <thead>
                                                        <tr>
                                                            <th scope="col">Offer Letter</th>
                                                            <th scope="col">Download</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    @foreach(Session::get('user_data') as $doc)
                                                        <tr>
                                                            <td>{{ $doc }}</td>
                                                            <td><a href="{{ route('docview','') }}/{{ $doc }}" target="_blank"><span class="badge badge-success">View</span></a></td>
                                                            @if($message = Session::get('error'))
                                                                <div class="alert alert-danger alert-dismissible fade in" role="alert">
                                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                                        <span aria-hidden="true">×</span>
                                                                    </button>
                                                                    <strong>Error!</strong> {{ $message }}
                                                                </div>
                                                            @endif
                                                            {!! Session::forget('error') !!}
                                                            @if($message = Session::get('success'))
                                                                <div class="alert alert-info alert-dismissible fade in" role="alert">
                                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                                        <span aria-hidden="true">×</span>
                                                                    </button>
                                                                    <strong>Success!</strong> {{ $message }}
                                                                </div>
                                                            @endif
                                                            {!! Session::forget('success') !!}
                                                            <td><form action="{{route('razorpaypayment')}}" method="POST" >                        
                                                                <script src="https://checkout.razorpay.com/v1/checkout.js"
                                                                        data-key="{{ env('RAZORPAY_KEYID') }}"
                                                                        data-amount="50000"
                                                                        data-buttontext="Pay"
                                                                        data-name="Future Alert"
                                                                        data-description="Let's Move Together"
                                                                        data-image="{{ asset('frontend/assets/images/falert.png') }}"
                                                                        data-prefill.name="name"
                                                                        data-prefill.email="email"
                                                                        data-theme.color="#2f55d4">
                                                                </script>
                                                                <input type="hidden" name="_token" value="{!!csrf_token()!!}">
                                                            </form></td>
                                                            <!-- <td><a href="{{route('razorpaypayment')}}" target=""><span class="badge badge-info">Pay</span></a></td> -->
                                                        </tr>
                                                    @endforeach
                                                    </tbody>
                                                </table>
                                            </div>      
                                        </div>
                                    </div>
                                </div>
                            </div>
                            @endif
                        </div>
                    </div>
                </div>
                 <!-- Javascripts -->
                <script src="{{ asset('dashboard-theme/assets/plugins/jquery/jquery-3.1.0.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/plugins/bootstrap/popper.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/plugins/bootstrap/js/bootstrap.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/plugins/chartjs/chart.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/plugins/apexcharts/dist/apexcharts.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/js/lime.min.js') }}"></script>
                <script src="{{ asset('dashboard-theme/assets/js/pages/dashboard.js') }}"></script> 
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/documentview.blade.php
<!DOCTYPE html>
<html>
    <head>
    <title>Future @ Alert</title>
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.12.313/build/pdf.min.js"></script>
    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
    </head>
    <body>
        <canvas id="the-canvas" style="border:1px solid black;"></canvas>
        <script>
           
        var url = 'https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf';
        
        // // Loaded via <script> tag, create shortcut to access PDF.js exports.
        var pdfjsLib = window['pdfjs-dist/build/pdf'];

        // The workerSrc property shall be specified.
        pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';
 
        // Asynchronous download of PDF
        var loadingTask = pdfjsLib.getDocument(url);
        loadingTask.promise.then(function(pdf) {
        console.log('PDF loaded');
        
            // Fetch the first page
            var pageNumber = 1;
            pdf.getPage(pageNumber).then(function(page) {
                console.log('Page loaded');

                var scale = 1.5;
                var viewport = page.getViewport({scale: scale});

                // Prepare canvas using PDF page dimensions
                var canvas = document.getElementById('the-canvas');
                var context = canvas.getContext('2d');
                canvas.height = viewport.height;
                canvas.width = viewport.width;

                // Render PDF page into canvas context
                var renderContext = {
                    background: 'rgba(0,0,0,0)',
                    canvasContext: context,
                    viewport: viewport
                };
                var renderTask = page.render(renderContext);
                renderTask.promise.then(function () {
                    console.log('Page rendered');
                });
            });
        }, function (reason) {
            // PDF loading error
            console.error(reason);
        });
        </script>
    </body>
</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/register-email.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- favicon -->
        <link rel="shortcut icon" href="{{ asset('frontend/assets/images/favicon.ico') }}">
        <!-- Bootstrap -->
        <link href="{{ asset('frontend/assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
        <!-- Font -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700&display=swap" rel="stylesheet">
        <!-- Main Css -->
        <link href="{{ asset('frontend/assets/css/style.css') }}" rel="stylesheet" type="text/css" />
    </head>

    <body style="font-family: Nunito, sans-serif; font-size: 15px; font-weight: 400;">
        <!-- Loader -->
        <!-- <div id="preloader">
            <div id="status">
                <div class="spinner">
                    <div class="double-bounce1"></div>
                    <div class="double-bounce2"></div>
                </div>
            </div>
        </div> -->
        <!-- Loader -->

        <!-- Hero Start -->
        <section style="align-items: center; padding: 150px 0;">
            <div class="container">
                <div class="row" style="justify-content: center;">
                    <div class="col-lg-6 col-md-8">
                        <table style="box-sizing: border-box; width: 100%; border-radius: 6px; overflow: hidden; background-color: #fff; box-shadow: 0 0 3px rgba(60, 72, 88, 0.15);">
                            <thead>
                                <tr style="background-color: #2f55d4; padding: 3px 0; line-height: 68px; text-align: center; color: #fff; font-size: 24px; font-weight: 700; letter-spacing: 1px;">
                                    <th scope="col"><img src="{{ asset('frontend/assets/images/falert.png') }}" height="24" alt="logo"></th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr>
                                    <td style="padding: 48px 24px 0; color: #161c2d; font-size: 18px; font-weight: 600;">
                                        Hello, {{$name}}
                                    </td>
                                </tr></br>
                                <tr>
                                    <td style="padding: 15px 24px 15px; color: #8492a6;">
                                        Thank you for registering, Your account details are as follows :</br></br>
                                        
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 15px 24px 15px; color: #8492a6;">
                                        Username :  {{$email}}.</br>
                                        Password :  {{$password}}.
                                    </td>
                                    
                                </tr>
                                <tr>
                                    <td style="padding: 15px 24px 15px; color: #8492a6;">
                                        To signin please click the button below :
                                    </td>
                                </tr>

                                <tr>
                                    <td style="padding: 15px 24px;">
                                        <a href="{{route('login')}}" class="btn-primary" style="padding: 8px 20px; outline: none; text-decoration: none; font-size: 16px; letter-spacing: 0.5px; transition: all 0.3s; font-weight: 600; border-radius: 6px;">Sign In</a>
                                    </td>
                                </tr>

                                <tr>
                                    <td style="padding: 15px 24px 0; color: #8492a6;">
                                       
                                        Thank you for choosing Future Alert.
                                    </td>
                                </tr>

                                <tr>
                                    <td style="padding: 15px 24px 15px; color: #8492a6;">
                                        Future Alert <br> Support Team
                                    </td>
                                </tr>

                                <tr>
                                    <td style="padding: 16px 8px; color: #8492a6; background-color: #f8f9fc; text-align: center;">
                                        © 2019-20 Future Alert.
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!--end col-->
                </div><!--end row-->
            </div> <!--end container-->
        </section><!--end section-->
        <!-- Hero End -->

        <!-- javascript -->
        <script src="js/jquery-3.5.1.min.js"></script>
        <script src="js/bootstrap.bundle.min.js"></script>
        <!-- Icons -->
        <script src="js/feather.min.js"></script>
        <!-- Main Js -->
        <script src="js/app.js"></script>
    </body>
</html>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>